export const BUILDING_ID = {
  METAL_MINE: 1,
  CRYSTAL_MINE: 2,
  DEUTERIUM_SYNTHESIZER: 3,
  SOLAR_PLANT: 4,
  FUSION_REACTOR: 12,
  METAL_STORAGE: 22,
  CRYSTAL_STORAGE: 23,
  DEUTERIUM_STORAGE: 24,
  ROBOTICS_FACTORY: 14,
  SHIPYARD: 21,
  RESEARCH_LAB: 31,
  ALLIANCE_DEPOT: 34,
  MISSILE_SILO: 44,
  NANITE_FACTORY: 15,
  TERRAFORMER: 33,
  SPACE_DOCK: 36,
} as const;

export type BuildingId = (typeof BUILDING_ID)[keyof typeof BUILDING_ID];
