FROM golang:1.26-alpine AS builder
RUN apk add --no-cache git
RUN git clone --branch develop --depth 1 https://github.com/alaingilbert/ogame.git /go/src/ogame \
    && cd /go/src/ogame \
    && go install ./cmd/ogamed

FROM alpine:3.21
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/ogamed /app/ogamed
WORKDIR /app
CMD ["./ogamed"]