FROM golang:1.26-alpine AS builder
RUN apk add --no-cache git
RUN git clone --branch develop --depth 1 https://github.com/alaingilbert/ogame.git /go/src/ogame

COPY patch-bearer-token.go /tmp/patch-bearer-token.go
RUN cd /go/src/ogame && \
    CGO_ENABLED=0 go run /tmp/patch-bearer-token.go

RUN cd /go/src/ogame && go install ./cmd/ogamed

FROM alpine:3.21
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/bin/ogamed /app/ogamed
WORKDIR /app
CMD ["./ogamed"]
