ALTER TABLE planets ADD COLUMN image_type TEXT NOT NULL DEFAULT '';

ALTER TABLE resources ADD COLUMN metal_storage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resources ADD COLUMN crystal_storage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resources ADD COLUMN deuterium_storage INTEGER NOT NULL DEFAULT 0;
ALTER TABLE resources ADD COLUMN metal_production REAL NOT NULL DEFAULT 0;
ALTER TABLE resources ADD COLUMN crystal_production REAL NOT NULL DEFAULT 0;
ALTER TABLE resources ADD COLUMN deuterium_production REAL NOT NULL DEFAULT 0;
